on: [push]

jobs:
  powershell_job:
    runs-on: windows-latest
    name: Remove Active Layers of Workflows
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: RemoveActiveLayers
      uses: ./actions\removeActiveLayers/
      with:
        tenantId: ''
        clientId: ''
        clientSecret: ''
        environmentUrl: ''
        filter: ''
  second_job:
    runs-on: windows-latest
    name: Move Solution Components
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Move Solution Components
      uses: ./actions\moveSolutionComponents/
      with:
        authType: 'ClientSecret'
        targetCRMURL: ''
        clientId: ''
        clientSecret: ''
        sourceSolutionName: ''
        targetSolutionName: ''
  third_job:
    runs-on: windows-latest
    name: Enable Multiple Flows
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Enable Multiple Flows
      uses: ./actions\enableMultipleFlows/
      with:
        envName: ''
        flowid: ''
        user: ''
        pass: ''
